### PR TITLE
[ADS-2794] feat: add new component PopoverWithRef

### LINKED ISSUE #852: Allow popover to render based on a external reference
Post the migration of Popover to react-popover, it would be nice to extend the component to accept a external ref and render based on the ref position. There are a few usages available on the library itself.

## Types of issue

- [ ] Bug (High impact or critical to a production build)
- [ ] Bug (Low impact or not working as expected)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Something else (idea, build tool, documentation improvement)

### PR DESCRIPTION
**Pull request by superpower1**
## Description

Popover.WithRef will accept `refElement` and render the popover based on the position of that element.

Fixes #852 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: src/components/third-party/PopoverWithRef/index.jsx [hunk 1]
```diff
@@ -0,0 +1,77 @@
...
+
+class PopoverWithRef extends React.PureComponent {
+  render() {
+    const { theme, title, dts, popoverClassNames, popoverContent, refElement, modifiers, wrapperStyles } = this.props;
+    const themeClass = _.includes(themes, theme) ? `popover-${theme}` : 'popover-light';
+    const popoverClass = classnames('aui--popover-wrapper', themeClass, popoverClassNames);
+
+    if (!this.props.isOpen) return null;
+
+    return ReactDOM.createPortal(
```
Comment (lightbringer1991) [inline src/components/third-party/PopoverWithRef/index.jsx]: this will always render Popover at the end of `body`. Is this a desired output?

Comment (superpower1) [reply src/components/third-party/PopoverWithRef/index.jsx]: Yes, popover will be rendered at a separate DOM and use absolute position of the `refElement` to decide where to place.

Comment (lightbringer1991) [reply src/components/third-party/PopoverWithRef/index.jsx]: you seem to not using any state, so I guess it can be changed to a functional component

File: src/components/third-party/PopoverWithRef/index.jsx [hunk 2]
```diff
@@ -0,0 +1,77 @@
...
+            <div
+              className="aui--popover-arrow"
+              data-placement={placement}
+              ref={arrowProps.ref}
+              style={{ ...arrowProps.style, ...this.props.arrowStyles }}
+            />
+          </div>
+        )}
+      </Popper>,
+      document.body
```
Comment (veegandhi) [inline src/components/third-party/PopoverWithRef/index.jsx]: Like `Popover`, this should receive the container from the user.

File: src/components/third-party/Popover/WithRef.jsx [hunk 3]
```diff
@@ -0,0 +1,71 @@
...
+  wrapperStyles,
+  placement,
+  isOpen,
+  arrowStyles,
+  getContainer,
+  popperRef,
+}) => {
+  const themeClass = _.includes(themes, theme) ? `popover-${theme}` : 'popover-light';
+  const popoverClass = classnames('aui--popover-wrapper', themeClass, popoverClassNames);
+  const boundariesElement = getContainer ? getContainer() : document.body;
```
Comment (xiaofan2406) [inline src/components/third-party/Popover/WithRef.jsx]: Please avoid using `document.body` as the root target for `createPortal` API.

grid_ repo does it for other reasons (should be re-visited too tbh).

You can create a `Portal` component that creates a div on mount, and cleans up on unmount.

**Comment by xiaofan2406** [comment]
Not sure how this decision of creating yet another component that does popover was arrived, maybe its worth thinking about the most common usages we have, and check against the current API to see if the two component make sense to be separate or if there are any other pieces are missing

**Comment by veegandhi** [comment]
> Not sure how this decision of creating yet another component that does popover was arrived, maybe its worth thinking about the most common usages we have, and check against the current API to see if the two component make sense to be separate or if there are any other pieces are missing

We do that in the review session. Would encourage you to attend them

**Comment by xiaofan2406** [comment]
all good if this the api we decided to go with, was just curious.

File: src/components/third-party/Popover/WithRef.jsx (hunk 3 above)
Comment (veegandhi) [reply src/components/third-party/Popover/WithRef.jsx]: Resolving this per offline discussion

**Comment by veegandhi** [comment]
Will need an example in the documentation explaining the usage difference in the api.

File: src/components/third-party/Popover/index.jsx [hunk 4]
```diff
@@ -94,39 +96,17 @@ class Popover extends React.PureComponent {
...
-                <div
-                  className="aui--popover-arrow"
-                  data-placement={placement}
-                  ref={arrowProps.ref}
-                  style={{ ...arrowProps.style, ...arrowStyles }}
-                />
-              </div>
-            )}
-          </Popper>,
+            modifiers={this.props.modifiers}
```
Comment (veegandhi) [inline src/components/third-party/Popover/index.jsx]: `modifiers` implementation should not change here. On existing api, it should still `preventOverflow` and get `boundariesElement` and then override modifiers by props.

File: src/components/third-party/Popover/index.jsx [hunk 5]
```diff
@@ -94,39 +96,17 @@ class Popover extends React.PureComponent {
...
+            boundariesElement={this.getBoundedContainer()}
+            popoverClass={popoverClass}
+            wrapperStyles={this.props.wrapperStyles}
+            dts={dts}
+            title={title}
+            popoverContent={popoverContent}
+            arrowStyles={arrowStyles}
```
Comment (veegandhi) [inline src/components/third-party/Popover/index.jsx]: `arrowStyles` configuration should not different between both api.

Comment (veegandhi) [reply src/components/third-party/Popover/index.jsx]: The above applies to `popoverClass`  too.

**Comment by veegandhi** [comment]
@superpower1 - Running local throws a couple of console warnings. Can you resolve it?

File: src/components/third-party/Popover/index.jsx (hunk 4 above)
Comment (superpower1) [reply src/components/third-party/Popover/index.jsx]: > `modifiers` implementation should not change here. On existing api, it should still `preventOverflow` and get `boundariesElement` and then override modifiers by props.

No, it doesn't change, I just move the implementation to `Popper.jsx`

File: src/components/third-party/Popover/index.jsx (hunk 5 above)
Comment (superpower1) [reply src/components/third-party/Popover/index.jsx]: Same as the `modifier` above, I did not change them, just move them to a separate file `Popper.jsx`.

**Comment by superpower1** [comment]
> @superpower1 - Running local throws a couple of console warnings related to `Popover` . Can you resolve it?

Yeah, I've resolved it.

File: www/examples/PopoverWithRefExample.jsx [hunk 6]
```diff
@@ -0,0 +1,144 @@
...
+
+  togglePopover = () =>
+    this.setState(prevState => ({
+      isOpen: !prevState.isOpen,
+    }));
+
+  render() {
+    return (
+      <>
+        <h3>Popover with Ref</h3>
```
Comment (veegandhi) [inline www/examples/PopoverWithRefExample.jsx]: remove this, component name get the title.

File: www/examples/PopoverWithRefExample.jsx [hunk 7]
```diff
@@ -0,0 +1,144 @@
...
+            isOpen={this.state.isOpen}
+          />
+        )}
+      </>
+    );
+  }
+}
+
+const exampleProps = {
+  componentName: 'Popover With Ref',
```
Comment (veegandhi) [inline www/examples/PopoverWithRefExample.jsx]: Popover with external ref
